/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'scott' at '2/7/16 5:20 PM' with Gradle 2.6
 *
 * @author scott, @date 2/7/16 5:20 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
