/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'scott' at '2/7/16 5:20 PM' with Gradle 2.6
 *
 * @author scott, @date 2/7/16 5:20 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
